// Solo NEET SS — Shared Type Definitions
// All domain models, repository interfaces, and Express augmentations.

import type { Low } from 'lowdb';
import type { Request, Response, NextFunction } from 'express';

// ======================== EXPRESS AUGMENTATION ========================

declare global {
    namespace Express {
        interface Request {
            userId: string;
            id: string;
            user?: User;
        }
    }
}

// ======================== DOMAIN MODELS ========================

export interface User {
    id: string;
    username: string;
    email: string;
    password: string | null;
    hunterName: string;
    avatar?: string | null;
    googleId?: string;
    fcmTokens?: string[];
    notificationPrefs?: NotificationPrefs;
    isAdmin?: boolean;
    isPremium?: boolean;
    subscriptionPlan?: string;
    subscriptionEnd?: string;
    subscriptionId?: string;
    lastActive?: string;
    createdAt: string;
}

export interface NotificationPrefs {
    dailyReminder?: boolean;
    streakReminder?: boolean;
    challengeNotify?: boolean;
    reminderHour?: number;
}

export interface SubjectProgress {
    answered: number;
    correct: number;
}

export interface Progress {
    userId: string;
    level: number;
    currentXP: number;
    totalXP: number;
    questionsAnswered: number;
    correctAnswers: number;
    currentStreak: number;
    bestStreak: number;
    dungeonsCleared: number;
    perfectDungeons: number;
    achievements: string[];
    subjectProgress: Record<string, SubjectProgress>;
    lastUpdated?: string;
}

export interface LeaderboardEntry {
    userId: string;
    username: string;
    hunterName: string;
    level: number;
    totalXP: number;
    rank: string;
}

export interface QuestionSource {
    type: string;
    pmid: string;
    title: string;
    journal: string;
    year: string;
    generatedAt?: string;
    llmProvider?: string;
    llmModel?: string;
}

export interface GeneratedQuestion {
    id: string;
    question: string;
    options: string[];
    correct: number;
    difficulty: 'easy' | 'medium' | 'hard';
    xp: number;
    explanation: string;
    source?: QuestionSource;
    specialty?: string;
    generatedBy?: string;
    generatedAt?: string;
    llmProvider?: string;
    autoGenerated?: boolean;
    aiGenerated?: boolean;
    reviewed?: boolean;
    approved?: boolean;
    reviewedAt?: string;
    reviewedBy?: string;
}

export interface SRSAttempt {
    correct: boolean;
    timeMs: number;
    quality: number;
    date: string;
}

export interface SRSRecord {
    questionId: string;
    userId: string;
    repetition: number;
    easeFactor: number;
    interval: number;
    nextReview: string;
    lastAttempt: string | null;
    attempts: SRSAttempt[];
    createdAt: string;
    quality?: number;
}

export interface Payment {
    id: string;
    userId: string;
    orderId: string;
    paymentId: string;
    planId: string;
    amount: number;
    status: string;
    createdAt: string;
}

export interface Group {
    id: string;
    name: string;
    description: string;
    ownerId: string;
    memberIds: string[];
    maxMembers: number;
    createdAt: string;
}

export interface Challenge {
    id: string;
    code: string;
    creatorId: string;
    opponentId: string | null;
    subject: string;
    questionCount: number;
    status: 'waiting' | 'active' | 'completed';
    createdAt: string;
}

export interface PubMedArticle {
    pmid: string;
    title: string;
    abstract: string;
    authors: string;
    journal: string;
    year: string;
}

export interface BattleQuestion {
    id: string;
    question: string;
    options: string[];
    correct: number;
    subject: string;
    explanation: string;
    reference: string;
}

// ======================== DATABASE ========================

export interface DatabaseData {
    users: User[];
    progress: Progress[];
    leaderboard: LeaderboardEntry[];
    generatedQuestions: GeneratedQuestion[];
    srsRecords?: SRSRecord[];
    payments?: Payment[];
    groups?: Group[];
    challenges?: Challenge[];
}

// ======================== REPOSITORY INTERFACES ========================

export interface UserRepository {
    findById(id: string): Promise<User | null>;
    findByEmail(email: string): Promise<User | null>;
    findByGoogleId(googleId: string): Promise<User | null>;
    findByEmailOrUsername(email: string, username: string): Promise<User | null>;
    create(userData: User): Promise<User>;
    update(id: string, updates: Partial<User>): Promise<User | null>;
    getAll(): Promise<User[]>;
    findWithFCMTokens(): Promise<User[]>;
    findDailyReminderEligible(hour: number): Promise<User[]>;
    findStreakAtRisk(): Promise<User[]>;
    countNewSince(days: number): Promise<number>;
}

export interface ProgressRepository {
    findByUserId(userId: string): Promise<Progress | null>;
    create(record: Progress): Promise<Progress>;
    update(userId: string, updates: Partial<Progress>): Promise<Progress | null>;
    getAll(): Promise<Progress[]>;
}

export interface LeaderboardRepository {
    getTopPlayers(limit?: number): Promise<LeaderboardEntry[]>;
    findByUserId(userId: string): Promise<LeaderboardEntry | null>;
    getRank(userId: string): Promise<{ rank: number | null; entry: LeaderboardEntry | null; totalPlayers: number }>;
    create(entry: LeaderboardEntry): Promise<LeaderboardEntry>;
    update(userId: string, updates: Partial<LeaderboardEntry>): Promise<LeaderboardEntry | null>;
    getAll(): Promise<LeaderboardEntry[]>;
}

export interface GeneratedQuestionsRepository {
    add(question: GeneratedQuestion): Promise<GeneratedQuestion>;
    addBatch(questions: GeneratedQuestion[]): Promise<void>;
    findById(id: string): Promise<GeneratedQuestion | null>;
    list(filter?: { reviewed?: boolean }): Promise<GeneratedQuestion[]>;
    review(id: string, data: { approved: boolean; reviewedBy: string; specialty?: string }): Promise<GeneratedQuestion | null>;
    count(): Promise<number>;
    getProcessedPmids(): Promise<Set<string>>;
}

export interface SRSRecordsRepository {
    findByUserAndQuestion(userId: string, questionId: string): Promise<SRSRecord | null>;
    findByUser(userId: string): Promise<SRSRecord[]>;
    getAll(userId?: string): Promise<SRSRecord[]>;
    create(record: SRSRecord): Promise<SRSRecord>;
    upsert(userId: string, questionId: string, record: SRSRecord): Promise<SRSRecord>;
    exists(userId: string, questionId: string): Promise<boolean>;
    createBatch(records: SRSRecord[]): Promise<void>;
}

export interface PaymentsRepository {
    create(payment: Payment): Promise<Payment>;
    count(): Promise<number>;
}

export interface GroupsRepository {
    getAll(): Promise<Group[]>;
    findById(id: string): Promise<Group | null>;
    create(group: Group): Promise<Group>;
    addMember(groupId: string, userId: string): Promise<Group | null>;
    removeMember(groupId: string, userId: string): Promise<Group | null>;
}

export interface ChallengesRepository {
    create(challenge: Challenge): Promise<Challenge>;
    findByCode(code: string): Promise<Challenge | null>;
    activate(code: string, opponentId: string): Promise<Challenge | null>;
}

export interface SubscriptionActivation {
    planId: string;
    paymentId: string;
    orderId: string;
    amount: number;
    subscriptionEnd: string;
}

export interface DAL {
    users: UserRepository;
    progress: ProgressRepository;
    leaderboard: LeaderboardRepository;
    generatedQuestions: GeneratedQuestionsRepository;
    srsRecords: SRSRecordsRepository;
    payments: PaymentsRepository;
    groups: GroupsRepository;
    challenges: ChallengesRepository;
    createUserWithProgress(userData: User, progressData: Progress, leaderboardData: LeaderboardEntry): Promise<User>;
    saveProgressAndLeaderboard(userId: string, updates: Partial<Progress>): Promise<Progress | null>;
    activateSubscription(userId: string, data: SubscriptionActivation): Promise<User | null>;
    raw: Low<DatabaseData>;
}

// ======================== ROUTE DEPENDENCIES ========================

export interface RouteDeps {
    dal: DAL;
    JWT_SECRET: string;
    authMiddleware: (req: Request, res: Response, next: NextFunction) => void;
    adminMiddleware: (req: Request, res: Response, next: NextFunction) => void;
    authLimiter: (req: Request, res: Response, next: NextFunction) => void;
    isProduction: boolean;
    FRONTEND_URL: string;
}

// ======================== LLM / QUESTION GENERATION ========================

export interface GenerationResult {
    questions: GeneratedQuestion[];
    errors: GenerationError[];
    totalGenerated: number;
    totalErrors: number;
    provider?: string;
    model?: string;
}

export interface GenerationError {
    pmid: string;
    title: string;
    error: string;
}

export interface OllamaStatus {
    available: boolean;
    models?: string[];
    hasLlama3?: boolean;
    defaultModel?: string;
    error?: string;
}

export interface OllamaGenerateOptions {
    model?: string;
    temperature?: number;
    topK?: number;
    topP?: number;
    maxTokens?: number;
}

// ======================== PUSH NOTIFICATION ========================

export interface PushNotification {
    title?: string;
    body?: string;
    tag?: string;
    link?: string;
    data?: Record<string, string>;
}

// ======================== PAYMENT PLANS ========================

export interface Plan {
    id: string;
    name: string;
    amount: number;
    currency: string;
    duration: number;
}

// ======================== PVP ========================

export interface PvPPlayer {
    id: string;
    odid?: string;
    username: string;
    hunterName: string;
    level: number;
    avatar?: string | null;
    score?: number;
    answered?: number;
    ready?: boolean;
}

export interface BattleRoom {
    id: string;
    players: PvPPlayer[];
    questions: BattleQuestion[];
    currentQuestion: number;
    status: 'waiting' | 'countdown' | 'active' | 'finished';
    isRanked: boolean;
    startTime: number | null;
    answers: Record<string, { answer: number; isCorrect: boolean; points: number }>;
    finishedAt?: number;
}

export interface PrivateRoom {
    code: string;
    host: PvPPlayer;
    hostSocket: string;
    createdAt: number;
}

// ======================== BACKGROUND GENERATOR ========================

export interface GeneratorStats {
    totalGenerated: number;
    totalErrors: number;
    lastSpecialty: string | null;
    questionsToday: number;
}

export interface BackgroundGenerator {
    getStats(): GeneratorStats & { isRunning: boolean; lastRunTime: string | null; processedCount: number };
    forceRun(): Promise<void>;
    stop(): void;
}

// ======================== LOGGER ========================

export interface Logger {
    error(msg: string, meta?: Record<string, unknown>): void;
    warn(msg: string, meta?: Record<string, unknown>): void;
    info(msg: string, meta?: Record<string, unknown>): void;
    debug(msg: string, meta?: Record<string, unknown>): void;
    child(context: Record<string, unknown>): Logger;
}

// ======================== SRS RESULT ========================

export interface SRSResult {
    repetition: number;
    interval: number;
    easeFactor: number;
    nextReview: string;
    quality: number;
}
